spring.application.name=backendpractica

# --- Base de datos MySQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/hosteleria_practica?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=practica
spring.datasource.password=practica_pw123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Servidor ---
server.port=8081

# --- JWT ---
app.jwt.secret=cCBcYzRmZDkwMTIzNDU2Nzg5MHNlY3JldGtleUFuZ3VsYXJTcHJpbmdCb290SG9zdGVsZXJpYQ==
app.jwt.expiration-ms=86400000

# --- CORS ---
app.cors.allowed-origin=http://localhost:4200